CREATE TABLE autores (
  id SERIAL PRIMARY KEY,
  nome_artistico VARCHAR(50) NOT NULL,
  slug VARCHAR(50) NOT NULL,
  bio VARCHAR(10000) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  ativo BOOLEAN NOT NULL DEFAULT FALSE,
  id_usuario INTEGER DEFAULT NULL,
  data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
 );

ALTER TABLE autores
  ADD CONSTRAINT IDX_87d3f67c198076d9b665a453bb UNIQUE (nome_artistico)

